// Generated by CoffeeScript 1.6.3
(function() {
  require('coffee-script');
  require('./../lib/modelLoader.coffee');

  require('./../lib/functionLoader.coffee');
  var arr, func_url, getPINs, neighbours, s;
  
  
  s = "abcdefghijklmnopqrstuvwxyz0123456789";

  func_url = __F('url');

  neighbours = {
    1: s.split("")
  };

  getPINs = function(observed, prefix) {
    prefix = prefix || "";
    if (observed.length === 0) {
      return prefix;
    } else {
      return neighbours[observed[0]].reduce((function(acc, d) {
        return acc.concat(getPINs(observed.substring(1), prefix + d));
      }), []);
    }
  };

  arr = getPINs("111");

  arr.forEach((function(p) {
    func_url.addUUS({key:p})
  }));

}).call(this);
