module.exports = 
  id:"int"
  nick:"varchar(255)"
  head_pic:"varchar(255)"
  weibo_id:"bigint"
  weibo_token:"varchar(100)"
  weibo_refresh:"varchar(100)"
  card_id:"int"
  coin:
    type:"int"
    defaultValue:0
  is_admin:
    defaultValue:0
    type:"tinyint"
  sex:"varchar(5)"
  weibo_name:"varchar(50)"
  desc:"varchar(300)"
  bi:
    type:"int"
    defaultValue:5
  email:"varchar(100)"
  is_block:
    type:"tinyint"
    defaultValue:0